name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

    - name: Update Container in the Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_DEPLOYMENT_USER }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker stop broiler || true
          docker rm broiler || true
          docker run -d -p 5000:5000 -v /home/environments/.env-broiler:/broiler-model-api/.env -e PYTHONUNBUFFERED=1 --name broiler ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker image prune -f || true